language: go
go:
  - 1.8.x

install: make get-deps

before_script:
  - make clean
  - make vet

scripts:
  - make test
  - make gherkinize

notifications:
  email:
    recipients:
      - developer@wesovilabs.com
    on_success: always
    on_failure: always

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "dist/gherkinize"
  skip_cleanup: true
  on:
    tags: true
