language: go
go:
  - 1.8.x

install: make get-deps

before_script:
  - make clean
  - make vet

scripts:
  - make test
  - make gherkinize

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file:
    - "dist/gherkinize"
  on:
    repo: wesovilabs/gherkinize
    tags: true
    all_branches: true