language: go
go:
  - 1.8.x

install: make get-deps

before_script:
  - make clean
  - make vet

scripts:
  - make test
  - make gherkinize

notifications:
  email:
    recipients:
      - developer@wesovilabs.com
    on_success: always
    on_failure: always

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push origin --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file:
    - "dist/gherkinize"
  on:
    repo: wesovilabs/gherkinize
    tags: true
    all_branches: true

env:
  global:
    secure: $GH_TOKEN